# Generated by Django 5.2.10 on 2026-04-13 22:58

import django.core.validators
import django.db.models.deletion
import videos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0003_remove_student_grade_student_class_level_and_more'),
        ('subjects', '0003_remove_subject_teacher_alter_subject_code_and_more'),
        ('teachers', '0003_teacher_assigned_subjects_alter_teacher_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('lecture', 'Lecture'), ('tutorial', 'Tutorial'), ('review', 'Review'), ('lab', 'Lab / Demo'), ('other', 'Other')], db_index=True, default='lecture', max_length=32)),
                ('video_file', models.FileField(upload_to=videos.models.educational_video_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'mov', 'm4v', 'ogg'])])),
                ('duration_seconds', models.PositiveIntegerField(blank=True, help_text='Optional; clients may send duration after upload for progress %', null=True)),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='subjects.subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_videos', to='teachers.teacher')),
            ],
            options={
                'db_table': 'educational_videos',
                'ordering': ['subject', 'display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VideoProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_position_seconds', models.PositiveIntegerField(default=0, help_text='Last playback position for resume')),
                ('total_watch_seconds', models.PositiveIntegerField(default=0, help_text='Cumulative engaged watch time reported by the client')),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_progress', to='students.student')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='videos.video')),
            ],
            options={
                'db_table': 'video_progress',
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['subject', 'is_published', 'category'], name='educational_subject_8ab702_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['uploaded_by', 'is_published'], name='educational_uploade_acc745_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['student', 'updated_at'], name='video_progr_student_d3ff7c_idx'),
        ),
        migrations.AddIndex(
            model_name='videoprogress',
            index=models.Index(fields=['video', 'is_completed'], name='video_progr_video_i_53e0cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='videoprogress',
            constraint=models.UniqueConstraint(fields=('student', 'video'), name='uniq_video_progress_student_video'),
        ),
    ]
