# Generated by hand on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='target_classes',
            field=models.ManyToManyField(
                help_text='Target classes for this educational video.',
                related_name='videos',
                to='classes.schoolclass',
            ),
        ),
    ]
