# Generated by Django 5.2.10 on 2026-01-21 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0003_alter_parent_occupation_alter_parent_parent_id_and_more'),
        ('students', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='class_level',
            field=models.CharField(blank=True, help_text='Current class level (e.g., Grade 1, Grade 2, Form 1, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Student date of birth', null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Parent or guardian of this student', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='parents.parent'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(help_text='Unique identifier for the student', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(help_text='User account associated with this student', on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['student_id'], name='students_student_1ff8ed_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['class_level'], name='students_class_l_e7e475_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['parent'], name='students_parent__5d193d_idx'),
        ),
    ]
