# Generated by Django 5.2.10 on 2026-05-09 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_student_photo_face_registered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(blank=True, default=None, help_text='Unique identifier for the student. Auto-generated if left blank.', max_length=50, null=True, unique=True),
        ),
    ]
