# Generated by Django 5.2.10 on 2026-05-04 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='schoolclass',
            new_name='school_clas_name_6f3a01_idx',
            old_name='school_clas_name_idx',
        ),
        migrations.RenameIndex(
            model_name='schoolclass',
            new_name='school_clas_section_2af973_idx',
            old_name='school_clas_section_idx',
        ),
    ]
