# Generated by Django 5.2.10 on 2026-05-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_rename_school_clas_name_idx_school_clas_name_6f3a01_idx_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('name', 'section')},
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='description_ar',
            field=models.TextField(blank=True, default='', help_text='Optional description or notes about this class.', null=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='description_en',
            field=models.TextField(blank=True, default='', help_text='Optional description or notes about this class.', null=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='name_ar',
            field=models.CharField(help_text='Grade/class name (e.g., Grade 5, Year 10)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='name_en',
            field=models.CharField(help_text='Grade/class name (e.g., Grade 5, Year 10)', max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('name', 'section'), ('name_ar', 'section'), ('name_en', 'section')},
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['name_en'], name='school_clas_name_6f3a01_idx-en'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['name_ar'], name='school_clas_name_6f3a01_idx-ar'),
        ),
    ]
