"""
Django settings for smartSchool project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
from django.utils.translation import gettext_lazy as _

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-7j%&flu_o(0j3ee!n29yqi^7!6563outxsheck5p788*0*3u#f')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
X_FRAME_OPTIONS = 'SAMEORIGIN'


# Application definition

INSTALLED_APPS = [
    'daphne',
    'channels',
    'modeltranslation',          # must come before django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_seed',
    'rest_framework_simplejwt',
    'users',
    'students',
    'teachers',
    'parents',
    'subjects',
    'classes',
    'attendance',
    'exams',
    'reports',
    'videos',
    'notifications',
    'chatbot',
]

ASGI_APPLICATION = 'smartSchool.asgi.application'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',
    },
}

# Alert when exam percentage is below this value (student + parent).
NOTIFICATION_LOW_GRADE_PERCENT = float(os.getenv('NOTIFICATION_LOW_GRADE_PERCENT', '50'))

# At-Risk Student Detection thresholds
NOTIFICATION_AT_RISK_ABSENCE_THRESHOLD = int(os.getenv('NOTIFICATION_AT_RISK_ABSENCE_THRESHOLD', '3'))
NOTIFICATION_AT_RISK_ABSENCE_WINDOW_DAYS = int(os.getenv('NOTIFICATION_AT_RISK_ABSENCE_WINDOW_DAYS', '30'))
NOTIFICATION_AT_RISK_GRADE_PERCENT = float(os.getenv('NOTIFICATION_AT_RISK_GRADE_PERCENT', '50'))

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'smartSchool.middleware.APILanguageMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'smartSchool.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'smartSchool.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Get database configuration from environment variables
DB_NAME = os.getenv('DB_NAME', 'smart-school')
DB_USER = os.getenv('DB_USER', '')
DB_PASSWORD = os.getenv('DB_PASSWORD', '')
DB_HOST = os.getenv('DB_HOST', 'DESKTOP-2ASDU43\\SQLEXPRESS')
DB_PORT = os.getenv('DB_PORT', '')
DB_DRIVER = os.getenv('DB_DRIVER', 'ODBC Driver 17 for SQL Server')

# Build database configuration
# For Windows Authentication: leave USER and PASSWORD empty
# For SQL Server Authentication: provide USER and PASSWORD
# Note: For named instances (with \), don't specify PORT
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': DB_NAME,
        'HOST': DB_HOST,
        'OPTIONS': {
            'driver': DB_DRIVER,
        },
    }
}

# Only add PORT if it's specified and not using a named instance
# Named instances (containing \) don't use PORT
if DB_PORT and '\\' not in DB_HOST:
    DATABASES['default']['PORT'] = DB_PORT

# Add authentication based on provided credentials
if DB_USER and DB_PASSWORD:
    # SQL Server Authentication
    DATABASES['default']['USER'] = DB_USER
    DATABASES['default']['PASSWORD'] = DB_PASSWORD
    DATABASES['default']['OPTIONS']['extra_params'] = 'TrustServerCertificate=yes;'
else:
    # Windows Authentication (Trusted Connection)
    # Don't set USER or PASSWORD, and add Trusted_Connection to extra_params
    DATABASES['default']['OPTIONS']['extra_params'] = 'TrustServerCertificate=yes;Trusted_Connection=yes;'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('en', _('English')),
    ('ar', _('Arabic')),
]

LOCALE_PATHS = [
    BASE_DIR / 'locale',
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'users.User'

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20
}

# Simple JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'JTI_CLAIM': 'jti',
}

# Gemini API Key (used by chatbot)
GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '')

# Face Recognition Service Settings
FACE_RECOGNITION_SERVICE_URL = os.getenv('FACE_RECOGNITION_SERVICE_URL', 'http://localhost:8001')
FACE_RECOGNITION_TIMEOUT = int(os.getenv('FACE_RECOGNITION_TIMEOUT', '30'))
# Batch face detection (CNN model) can take much longer; default 120s
FACE_RECOGNITION_BATCH_TIMEOUT = int(os.getenv('FACE_RECOGNITION_BATCH_TIMEOUT', '120'))

# Media files (uploaded student photos, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')