# Generated by Django 5.2.10 on 2026-01-21 22:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_initial'),
        ('students', '0003_remove_student_grade_student_class_level_and_more'),
        ('subjects', '0003_remove_subject_teacher_alter_subject_code_and_more'),
        ('teachers', '0003_teacher_assigned_subjects_alter_teacher_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=2, help_text='Score achieved by the student', max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grade',
                'verbose_name_plural': 'Grades',
                'db_table': 'grades',
                'ordering': ['-created_at', 'exam'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The question text')),
                ('options', models.JSONField(help_text='List of answer options (e.g., ["Option A", "Option B", "Option C", "Option D"])')),
                ('correct_answer', models.PositiveIntegerField(help_text='Index (0-based) of the correct answer in options array', validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
                'db_table': 'questions',
                'ordering': ['exam', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['-created_at', 'subject'], 'verbose_name': 'Exam', 'verbose_name_plural': 'Exams'},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_date',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='exam_type',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='max_score',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='score',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='student',
        ),
        migrations.AddField(
            model_name='exam',
            name='duration',
            field=models.PositiveIntegerField(default=60, help_text='Exam duration in minutes', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='exam',
            name='teacher',
            field=models.ForeignKey(blank=True, help_text='Teacher who created this exam', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_exams', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(help_text='Name of the exam (e.g., "Midterm Exam 2024", "Final Quiz")', max_length=200),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(help_text='Subject this exam is for', on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='subjects.subject'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['subject'], name='exams_subject_a51ed5_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['teacher'], name='exams_teacher_5a83b9_idx'),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['created_at'], name='exams_created_18b74e_idx'),
        ),
        migrations.AddField(
            model_name='grade',
            name='exam',
            field=models.ForeignKey(help_text='Exam this grade is for', on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='exams.exam'),
        ),
        migrations.AddField(
            model_name='grade',
            name='student',
            field=models.ForeignKey(help_text='Student who took the exam', on_delete=django.db.models.deletion.CASCADE, related_name='exam_grades', to='students.student'),
        ),
        migrations.AddField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(help_text='Exam this question belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['student', 'exam'], name='grades_student_369c15_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['exam'], name='grades_exam_id_d1cfd3_idx'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['score'], name='grades_score_201cb3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='grade',
            unique_together={('student', 'exam')},
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['exam'], name='questions_exam_id_519196_idx'),
        ),
    ]
