# Generated by Django 5.2.10 on 2026-04-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_make_teacher_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='class_id',
            field=models.CharField(blank=True, default='', help_text='Class identifier (e.g., G10-A). Leave blank for all classes.', max_length=50),
        ),
        migrations.AddField(
            model_name='exam',
            name='exam_date',
            field=models.DateField(blank=True, help_text='Date the exam is scheduled or was held', null=True),
        ),
    ]
