# Generated by Django 5.2.10 on 2026-05-15 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_exam_exam_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='exam_type',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('midterm', 'Midterm'), ('final', 'Final'), ('assignment', 'Assignment')], default='quiz', help_text='Type of assessment', max_length=20),
        ),
    ]
