# Generated by Django 5.2.10 on 2026-05-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_remove_homework_and_oral_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='name_ar',
            field=models.CharField(help_text='Name of the exam (e.g., "Midterm Exam 2024", "Final Quiz")', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='exam',
            name='name_en',
            field=models.CharField(help_text='Name of the exam (e.g., "Midterm Exam 2024", "Final Quiz")', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options_ar',
            field=models.JSONField(help_text='List of answer options (e.g., ["Option A", "Option B", "Option C", "Option D"])', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='options_en',
            field=models.JSONField(help_text='List of answer options (e.g., ["Option A", "Option B", "Option C", "Option D"])', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_ar',
            field=models.TextField(help_text='The question text', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='text_en',
            field=models.TextField(help_text='The question text', null=True),
        ),
    ]
