# Generated by Django 5.2.10 on 2026-06-07 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_exam_name_ar_exam_name_en_question_options_ar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='total_grade',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Total grade of the exam (e.g. 50, 100)', max_digits=6, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
