# Generated by Django 5.2.10 on 2026-06-09 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0011_replace_grade_fk_with_charfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.CharField(choices=[('KG', 'Kindergarten'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], help_text='Grade level this exam is for (e.g., 1, 2, 3... 12, KG)', max_length=10),
        ),
    ]
