# Generated by Django 5.2.10 on 2026-06-09 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_schoolclass_unique_together_and_more'),
        ('exams', '0012_alter_exam_grade'),
        ('subjects', '0005_material_description_ar_material_description_en_and_more'),
        ('teachers', '0006_remove_department_and_specialization'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='Specific class group this exam is for. When set, grade is auto-derived from the class name.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='classes.schoolclass'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='grade',
            field=models.CharField(blank=True, choices=[('KG', 'Kindergarten'), ('1', 'Grade 1'), ('2', 'Grade 2'), ('3', 'Grade 3'), ('4', 'Grade 4'), ('5', 'Grade 5'), ('6', 'Grade 6'), ('7', 'Grade 7'), ('8', 'Grade 8'), ('9', 'Grade 9'), ('10', 'Grade 10'), ('11', 'Grade 11'), ('12', 'Grade 12')], default='', help_text='Grade level this exam is for (e.g., 1, 2, 3... 12, KG). Auto-populated from school_class if set.', max_length=10),
        ),
        migrations.AddIndex(
            model_name='exam',
            index=models.Index(fields=['school_class'], name='exams_school__5501a5_idx'),
        ),
    ]
