# Generated by Django 5.2.10 on 2026-01-21 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_subject_teacher_alter_subject_code_and_more'),
        ('teachers', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='assigned_subjects',
            field=models.ManyToManyField(blank=True, help_text='Subjects assigned to this teacher', related_name='teachers', to='subjects.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, help_text='Department the teacher belongs to', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Date when the teacher was hired', null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='specialization',
            field=models.CharField(blank=True, help_text='Teacher specialization or area of expertise', max_length=200),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.CharField(help_text='Unique identifier for the teacher', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(help_text='User account associated with this teacher', on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['teacher_id'], name='teachers_teacher_456fe5_idx'),
        ),
        migrations.AddIndex(
            model_name='teacher',
            index=models.Index(fields=['department'], name='teachers_departm_174d34_idx'),
        ),
    ]
