# Generated by Django 5.2.10 on 2026-05-15 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0005_teacher_assigned_classes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='teacher',
            name='teachers_departm_174d34_idx',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='department',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='specialization',
        ),
    ]
