# Generated by Django 5.2.10 on 2026-01-21 22:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parents', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='occupation',
            field=models.CharField(blank=True, help_text='Parent occupation', max_length=100),
        ),
        migrations.AlterField(
            model_name='parent',
            name='parent_id',
            field=models.CharField(help_text='Unique identifier for the parent', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='parent',
            name='relationship',
            field=models.CharField(blank=True, help_text='Relationship to student (e.g., Father, Mother, Guardian, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='parent',
            name='user',
            field=models.OneToOneField(help_text='User account associated with this parent', on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='parent',
            index=models.Index(fields=['parent_id'], name='parents_parent__758966_idx'),
        ),
    ]
