# Generated by Django 5.2.10 on 2026-04-13 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_initial'),
        ('teachers', '0003_teacher_assigned_subjects_alter_teacher_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='First day of the reporting week (inclusive)')),
                ('week_end', models.DateField(help_text='Last day of the reporting week (inclusive)')),
                ('scope', models.CharField(choices=[('SCHOOL', 'School'), ('TEACHER', 'Teacher')], db_index=True, max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('READY', 'Ready'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=10)),
                ('dedupe_key', models.CharField(editable=False, max_length=96, unique=True)),
                ('attendance_stats', models.JSONField(blank=True, default=dict)),
                ('academic_stats', models.JSONField(blank=True, default=dict)),
                ('exam_stats', models.JSONField(blank=True, default=dict)),
                ('charts_payload', models.JSONField(blank=True, default=dict)),
                ('insights', models.JSONField(blank=True, default=list)),
                ('comparison_prior_week', models.JSONField(blank=True, help_text='Delta vs the immediately preceding week of equal length', null=True)),
                ('error_message', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='weekly_reports/pdf/')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, help_text='Set when scope is TEACHER; null for school-wide', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weekly_reports', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Weekly Report',
                'verbose_name_plural': 'Weekly Reports',
                'db_table': 'weekly_reports',
                'ordering': ['-week_start', 'scope'],
                'indexes': [models.Index(fields=['week_start', 'scope'], name='weekly_repo_week_st_292906_idx'), models.Index(fields=['teacher', 'week_start'], name='weekly_repo_teacher_8c9794_idx')],
            },
        ),
    ]
