# Generated by Django 5.2.10 on 2026-05-08 23:30

import django.db.models.deletion
import subjects.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_remove_subject_teacher_alter_subject_code_and_more'),
        ('teachers', '0005_teacher_assigned_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to=subjects.models.material_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='subjects.subject')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_materials', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
                'db_table': 'materials',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subject'], name='materials_subject_c9c1a7_idx'), models.Index(fields=['uploaded_by'], name='materials_uploade_858e96_idx')],
            },
        ),
    ]
