# Generated by Django 5.2.10 on 2026-05-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='description_ar',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_ar',
            field=models.TextField(blank=True, help_text='Description of the subject', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='description_en',
            field=models.TextField(blank=True, help_text='Description of the subject', null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_ar',
            field=models.CharField(help_text='Name of the subject (e.g., Mathematics, English, Science)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='name_en',
            field=models.CharField(help_text='Name of the subject (e.g., Mathematics, English, Science)', max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name_en'], name='subjects_name_ff98e0_idx-en'),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['name_ar'], name='subjects_name_ff98e0_idx-ar'),
        ),
    ]
