# Generated by Django 5.2.10 on 2026-06-11 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_alter_schoolclass_unique_together_and_more'),
        ('students', '0008_student_id_filtered_unique'),
        ('subjects', '0006_material_target_classes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAWN', 'Withdrawn'), ('COMPLETED', 'Completed'), ('SUSPENDED', 'Suspended')], default='ACTIVE', help_text='Current enrollment status', max_length=20)),
                ('enrollment_date', models.DateField(auto_now_add=True, help_text='Date when the enrollment was created')),
                ('withdrawal_date', models.DateField(blank=True, help_text='Date when the student withdrew (set automatically on WITHDRAWN)', null=True)),
                ('academic_year', models.CharField(blank=True, default='', help_text='Academic year label (e.g., 2025-2026)', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes about this enrollment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school_class', models.ForeignKey(blank=True, help_text='The class/grade group at the time of enrollment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subject_enrollments', to='classes.schoolclass')),
                ('student', models.ForeignKey(help_text='The student enrolled in the subject', on_delete=django.db.models.deletion.CASCADE, related_name='subject_enrollments', to='students.student')),
                ('subject', models.ForeignKey(help_text='The subject the student is enrolled in', on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Subject Enrollment',
                'verbose_name_plural': 'Subject Enrollments',
                'db_table': 'subject_enrollments',
                'ordering': ['student', 'subject'],
                'indexes': [models.Index(fields=['student'], name='subject_enr_student_74c93f_idx'), models.Index(fields=['subject'], name='subject_enr_subject_b6ea07_idx'), models.Index(fields=['school_class'], name='subject_enr_school__6eb9ab_idx'), models.Index(fields=['status'], name='subject_enr_status_49ac6c_idx'), models.Index(fields=['academic_year'], name='subject_enr_academi_d03c58_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('academic_year__gt', '')), fields=('student', 'subject', 'academic_year'), name='uniq_student_subject_academic_year'), models.UniqueConstraint(condition=models.Q(('academic_year', '')), fields=('student', 'subject'), name='uniq_student_subject_no_year')],
            },
        ),
    ]
