# Generated by Django 5.2.10 on 2026-04-13 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allow_low_grade', models.BooleanField(default=True)),
                ('allow_attendance', models.BooleanField(default=True)),
                ('allow_student_report', models.BooleanField(default=True)),
                ('allow_weekly_report', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('LOW_GRADE', 'Low grade alert'), ('ATTENDANCE', 'Attendance alert'), ('NEW_STUDENT_REPORT', 'New student report'), ('NEW_WEEKLY_REPORT', 'New weekly report'), ('SYSTEM', 'System')], db_index=True, max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, help_text='Optional key to avoid duplicate alerts (e.g. same absence day).', max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notificatio_recipie_2d3764_idx'), models.Index(fields=['recipient', 'read_at'], name='notificatio_recipie_8dcb32_idx')],
            },
        ),
    ]
