# Generated by Django 5.2.10 on 2026-05-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='body_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('LOW_GRADE', 'Low Grade'), ('ATTENDANCE', 'Attendance'), ('NEW_STUDENT_REPORT', 'New Student Report'), ('NEW_WEEKLY_REPORT', 'New Weekly Report'), ('SYSTEM', 'System')], db_index=True, max_length=32),
        ),
    ]
