# Generated by hand on 2026-06-06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_body_ar_notification_body_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('LOW_GRADE', 'Low Grade'),
                    ('ATTENDANCE', 'Attendance'),
                    ('EXAM_REMINDER', 'Exam Reminder'),
                    ('NEW_STUDENT_REPORT', 'New Student Report'),
                    ('NEW_WEEKLY_REPORT', 'New Weekly Report'),
                    ('SYSTEM', 'System'),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='allow_exam_reminder',
            field=models.BooleanField(default=True),
        ),
    ]
