# Generated by hand on 2026-06-09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_exam_reminder_type'),
    ]

    operations = [
        # ── Add AT_RISK to notification_type choices ──────────────────────────
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('ATTENDANCE', 'Attendance'),
                    ('LOW_GRADE', 'Low Grade'),
                    ('AT_RISK', 'At-Risk Student'),
                    ('EXAM_REMINDER', 'Exam Reminder'),
                    ('NEW_STUDENT_REPORT', 'New Student Report'),
                    ('NEW_WEEKLY_REPORT', 'New Weekly Report'),
                    ('SYSTEM', 'System'),
                ],
                db_index=True,
                max_length=32,
            ),
        ),

        # ── Add student FK to Notification (for role-based filtering) ─────────
        migrations.AddField(
            model_name='notification',
            name='student',
            field=models.ForeignKey(
                blank=True,
                help_text='Student related to this notification (enables role-based filtering).',
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='notifications',
                to='students.student',
            ),
        ),

        # ── Add index on (student, -created_at) ──────────────────────────────
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['student', '-created_at'], name='notificatio_student_8f3764_idx'),
        ),

        # ── Add allow_at_risk preference toggle ──────────────────────────────
        migrations.AddField(
            model_name='notificationpreference',
            name='allow_at_risk',
            field=models.BooleanField(default=True),
        ),

        # ── Add allow_system preference toggle ───────────────────────────────
        migrations.AddField(
            model_name='notificationpreference',
            name='allow_system',
            field=models.BooleanField(default=True),
        ),
    ]