# Generated by Django 5.2.10 on 2026-06-11 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_at_risk_student_fk'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_student_ecaed0_idx',
            old_name='notificatio_student_8f3764_idx',
        ),
    ]
