# Generated by Django 5.2.10 on 2026-01-21 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('students', '0003_remove_student_grade_student_class_level_and_more'),
        ('teachers', '0003_teacher_assigned_subjects_alter_teacher_department_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
        migrations.AddField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('face_recognition', 'FaceRecognition')], default='manual', help_text='Source of attendance: Manual entry or Face Recognition', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(help_text='Date of attendance'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(blank=True, help_text='Teacher who marked this attendance (if manual)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes about the attendance'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present'), ('absent', 'Absent')], default='present', help_text='Attendance status: Present or Absent', max_length=10),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(help_text='Student for this attendance record', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['student', 'date'], name='attendance_student_0943ef_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date'], name='attendance_date_d460ba_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['status'], name='attendance_status_a068a7_idx'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['source'], name='attendance_source_5efbc7_idx'),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='subject',
        ),
    ]
