# Generated by Django 5.2.10 on 2026-01-30 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_unique_together_attendance_source_and_more'),
        ('students', '0003_remove_student_grade_student_class_level_and_more'),
        ('teachers', '0003_teacher_assigned_subjects_alter_teacher_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the attendance session')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', help_text='Current status of the session', max_length=20)),
                ('class_name', models.CharField(blank=True, help_text='Class or subject name for this session', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the session')),
                ('total_faces_detected', models.IntegerField(default=0, help_text='Total number of faces detected across all images')),
                ('total_matches', models.IntegerField(default=0, help_text='Total number of successful face matches')),
                ('total_attendance_marked', models.IntegerField(default=0, help_text='Total number of attendance records created')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instructor', models.ForeignKey(help_text='Instructor who started this attendance session', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='teachers.teacher')),
            ],
            options={
                'verbose_name': 'Attendance Session',
                'verbose_name_plural': 'Attendance Sessions',
                'db_table': 'attendance_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='attendance',
            name='session',
            field=models.ForeignKey(blank=True, help_text='Attendance session this record belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='attendance.attendancesession'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['session'], name='attendance_session_4b3d35_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['instructor', 'date'], name='attendance__instruc_9eadd4_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['status'], name='attendance__status_23c6e5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesession',
            index=models.Index(fields=['date'], name='attendance__date_3a1d74_idx'),
        ),
    ]
