# Generated by Django 5.2.10 on 2026-05-04 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_attendancesession_attendance_session_and_more'),
        ('classes', '0002_rename_school_clas_name_idx_school_clas_name_6f3a01_idx_and_more'),
        ('teachers', '0005_teacher_assigned_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='school_class',
            field=models.ForeignKey(blank=True, help_text='Class whose students are tracked in this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='classes.schoolclass'),
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Instructor who started this attendance session (null for admin-created sessions)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_sessions', to='teachers.teacher'),
        ),
    ]
