# Generated by Django 5.2.10 on 2026-05-15 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancesession_school_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('face_recognition', 'Face Recognition')], default='manual', help_text='Source of attendance: Manual entry or Face Recognition', max_length=20),
        ),
    ]
